# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python 3.11 image as the base image
FROM python:3.11-slim as base

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Install pipenv and setup virtual environment
RUN pip install uv

# Set the working directory
WORKDIR /app

# Copy the entire project to the working directory
COPY . /app

# Create a virtual environment and install dependencies
RUN uv sync --frozen --no-dev --no-editable

# Expose any ports the app is expected to run on
EXPOSE 8000

# Set the entry point for running the server
ENTRYPOINT ["uv", "run", "src/mcp2mqtt/server.py"]